---
title: "Strojno učenje"
output: html_document
date: "2024-01-05"
---

```{r setup, include=FALSE}
library(tidyverse)
library(gridExtra)
library(GGally)
library(psych)
library(dplyr)
library(skimr)
library(caret)
library(corrplot)
library(randomForest)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


columns <- c('duration', 'director_facebook_likes', 'actor_1_facebook_likes','actor_2_facebook_likes', 'actor_3_facebook_likes', 'num_user_for_reviews', 'num_critic_for_reviews', 'num_voted_users', 'cast_total_facebook_likes', 'movie_facebook_likes', 'facenumber_in_poster', 'color', 'title_year', 'language', 'country', 'content_rating', 'aspect_ratio', 'gross', 'budget', 'imdb_score')

mldata <- data[,columns]

mldata <- na.omit(mldata)


```

```{r}
to_label <- c('color', 'language', 'country', 'content_rating', 'aspect_ratio')

label_encode <- function(column) {
  as.integer(factor(column, levels = unique(column)))
}

mldata[to_label] <- lapply(mldata[to_label], label_encode)
```


```{r}
sum(apply(mldata, 1, function(x) any(is.na(x))))
```


```{r}
mldata$score <- ifelse(mldata$imdb_score < 3.33, "loš", ifelse(mldata$imdb_score < 6.66, "osrednji", "dobar"))
mldata$score <- factor(mldata$score, levels = c("loš", "osrednji", "dobar"))
summary(mldata$score)
mldata$imdb_score <- NULL
```

```{r}
table(mldata$score)

ggplot(mldata, aes(x = score)) +
  geom_histogram(fill = "purple", color = "white", stat="count") +
  labs(x = "Uspjeh", y = "Broj filmova")
```


```{r}
set.seed(100)
trainingIndex <- createDataPartition(mldata$score, p = 0.8, list = FALSE)
training_set <- mldata[trainingIndex,]
testing_set <- mldata[-trainingIndex,]
```

```{r}
Model <- train(score ~ ., data = training_set,
               method = "svmPoly",
               na.action = na.omit,
               preProcess=c("scale","center"),
               trControl= trainControl(method="none"),
               tuneGrid = data.frame(degree=1,scale=1,C=1)
)
```

```{r}
confusionMatrix(predict(Model, testing_set), testing_set$score)
```

```{r}
Model_rf <- randomForest(score ~ ., data = training_set, ntree = 500, importance = TRUE)
confusionMatrix(predict(Model_rf, testing_set), testing_set$score)
importance(Model_rf)
```


```{r}
bad <- mldata[mldata$score=="loš",]
medium <- mldata[mldata$score=="osrednji",]
good <- mldata[mldata$score=="dobar",]
```


```{r}
library(ROSE)
over <- rbind(good, bad)
oversample <- ovun.sample(score~., data = over, method = "both", N = 3932)$data
```

```{r}
mldata <- rbind(mldata[mldata$score=="osrednji",], oversample)
```

```{r}
table(mldata$score)

ggplot(mldata, aes(x = score)) +
  geom_histogram(fill = "purple", color = "white", stat="count") +
  labs(x = "Uspjeh", y = "Broj filmova", title = "Podjela filmova po uspješnosti prije balansiranja skupova")
```

```{r}
set.seed(100)
trainingIndex <- createDataPartition(mldata$score, p = 0.8, list = FALSE)
training_set <- mldata[trainingIndex,]
testing_set <- mldata[-trainingIndex,]
```

```{r}
Model <- train(score ~ ., data = training_set,
               method = "svmPoly",
               na.action = na.omit,
               preProcess=c("scale","center"),
               trControl= trainControl(method="none"),
               tuneGrid = data.frame(degree=1,scale=1,C=1)
)
```

```{r}
confusionMatrix(predict(Model, testing_set), testing_set$score)
```

```{r}
Model_rf <- randomForest(score ~ ., data = training_set, ntree = 500, importance = TRUE)
confusionMatrix(predict(Model_rf, testing_set), testing_set$score)
importance(Model_rf)
varImpPlot(Model_rf, col = "blue", pch = 19, cex = 1, scale = TRUE)

```

```{r}
ggplot(mldata, aes(duration)) + 
  geom_histogram(bins = 100, position = "dodge", fill="purple" ) + facet_wrap(score~.) + labs(x = "Trajanje", y = "Broj filmova") + scale_x_continuous(limits = c(60, quantile(data$duration, 0.98, na.rm = TRUE)))
```

```{r}
ggplot(mldata, aes(num_critic_for_reviews)) + 
  geom_histogram(bins = 100, position = "dodge", fill="purple") + facet_wrap(score~.) + labs(x = "Broj negativnih recenzija", y = "Broj filmova") 
```

```{r}
mldata_filtered <- mldata[mldata$num_critic_for_reviews <= mldata$num_user_for_reviews & is.numeric(mldata$num_critic_for_reviews) &  is.numeric(mldata$num_user_for_reviews), ]

# Računanje postotka loših recenzija
mldata_filtered$percentage_negative_reviews <- with(mldata_filtered, 
    ifelse(num_user_for_reviews == 0, 0, (num_critic_for_reviews / num_user_for_reviews) * 100)
)

# Stvaranje grafikona
ggplot(mldata_filtered, aes(x = percentage_negative_reviews)) +
  geom_histogram(bins = 100, position = "dodge", fill = "purple") +
  facet_wrap(~score) +
  labs(x = "Postotak loših recenzija", y = "Broj filmova")
```

